# Created by: Dann_Soll
# A commands moderation plugin
# The plugin aimed to solve player-trust problems

# Discord Webhook URL
webhook-url: "YOUR_DISCORD_WEBHOOK_URL"

# Specific list of ignored commands to detect
commands:
  - "login"
  - "l"
  - "register"
  - "r"
  - "say"
  - "msg"
  - "changepassword"
  - "tell"
  - "bmpc"
  - "gamemode"
  - "bigbro"
  - "bigbrother"

# Specific list of players to monitor
players:
  - "Dann_Soll"
  - "ikeepkaIm"
  - "FyZzZen"
  - "vifoke"
  - "vifokeNOTzero4"